/vis/open OGL
/vis/drawVolume
/vis/viewer/set/autoRefresh false

# Add smooth trajectories
/vis/scene/add/trajectories smooth

# Filter: show only pion+
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add pi+

# Style: color pion+ as yellow
#/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
#/vis/modeling/trajectories/drawByParticleID-0/set pi+ yellow

# Accumulate tracks across events
/vis/scene/endOfEventAction accumulate

# Manual viewer refresh after events run
/vis/viewer/refresh
